        document.addEventListener("DOMContentLoaded", function() {

            console.group('%cwelcome.blade.php :: 769 =============================',
                'color: #273118; font-size: 1rem');
            console.log(jsVectorMap);
            console.groupEnd();

            const map = new jsVectorMap({
                selector: "#map-world",
                map: "world",
                backgroundColor: "transparent",
                regionStyle: {
                    initial: {
                        fill: "var(--tblr-bg-surface-secondary)",
                        stroke: "var(--tblr-border-color)",
                        strokeWidth: 2,
                    },
                },
                zoomOnScroll: false,
                zoomButtons: false,
                series: {
                    regions: [{
                        attribute: "fill",
                        scale: {
                            scale1: "color-mix(in srgb, transparent, var(--tblr-primary) 10%)",
                            scale2: "color-mix(in srgb, transparent, var(--tblr-primary) 20%)",
                            scale3: "color-mix(in srgb, transparent, var(--tblr-primary) 30%)",
                            scale4: "color-mix(in srgb, transparent, var(--tblr-primary) 40%)",
                            scale5: "color-mix(in srgb, transparent, var(--tblr-primary) 50%)",
                            scale6: "color-mix(in srgb, transparent, var(--tblr-primary) 60%)",
                            scale7: "color-mix(in srgb, transparent, var(--tblr-primary) 70%)",
                            scale8: "color-mix(in srgb, transparent, var(--tblr-primary) 80%)",
                            scale9: "color-mix(in srgb, transparent, var(--tblr-primary) 90%)",
                            scale10: "color-mix(in srgb, transparent, var(--tblr-primary) 100%)",
                        },
                        values: {
                            AF: "scale2",
                            AL: "scale2",
                            DZ: "scale4",
                            AO: "scale3",
                            AG: "scale1",
                            AR: "scale5",
                            AM: "scale1",
                            AU: "scale7",
                            AT: "scale5",
                            AZ: "scale3",
                            BS: "scale1",
                            BH: "scale2",
                            BD: "scale4",
                            BB: "scale1",
                            BY: "scale3",
                            BE: "scale5",
                            BZ: "scale1",
                            BJ: "scale1",
                            BT: "scale1",
                            BO: "scale2",
                            BA: "scale2",
                            BW: "scale2",
                            BR: "scale8",
                            BN: "scale2",
                            BG: "scale2",
                            BF: "scale1",
                            BI: "scale1",
                            KH: "scale2",
                            CM: "scale2",
                            CA: "scale7",
                            CV: "scale1",
                            CF: "scale1",
                            TD: "scale1",
                            CL: "scale4",
                            CN: "scale9",
                            CO: "scale5",
                            KM: "scale1",
                            CD: "scale2",
                            CG: "scale2",
                            CR: "scale2",
                            CI: "scale2",
                            HR: "scale3",
                            CY: "scale2",
                            CZ: "scale4",
                            DK: "scale5",
                            DJ: "scale1",
                            DM: "scale1",
                            DO: "scale3",
                            EC: "scale3",
                            EG: "scale5",
                            SV: "scale2",
                            GQ: "scale2",
                            ER: "scale1",
                            EE: "scale2",
                            ET: "scale2",
                            FJ: "scale1",
                            FI: "scale5",
                            FR: "scale8",
                            GA: "scale2",
                            GM: "scale1",
                            GE: "scale2",
                            DE: "scale8",
                            GH: "scale2",
                            GR: "scale5",
                            GD: "scale1",
                            GT: "scale2",
                            GN: "scale1",
                            GW: "scale1",
                            GY: "scale1",
                            HT: "scale1",
                            HN: "scale2",
                            HK: "scale5",
                            HU: "scale4",
                            IS: "scale2",
                            IN: "scale7",
                            ID: "scale6",
                            IR: "scale5",
                            IQ: "scale3",
                            IE: "scale5",
                            IL: "scale5",
                            IT: "scale8",
                            JM: "scale2",
                            JP: "scale9",
                            JO: "scale2",
                            KZ: "scale4",
                            KE: "scale2",
                            KI: "scale1",
                            KR: "scale6",
                            KW: "scale4",
                            KG: "scale1",
                            LA: "scale1",
                            LV: "scale2",
                            LB: "scale2",
                            LS: "scale1",
                            LR: "scale1",
                            LY: "scale3",
                            LT: "scale2",
                            LU: "scale3",
                            MK: "scale1",
                            MG: "scale1",
                            MW: "scale1",
                            MY: "scale5",
                            MV: "scale1",
                            ML: "scale1",
                            MT: "scale1",
                            MR: "scale1",
                            MU: "scale1",
                            MX: "scale7",
                            MD: "scale1",
                            MN: "scale1",
                            ME: "scale1",
                            MA: "scale3",
                            MZ: "scale2",
                            MM: "scale2",
                            NA: "scale2",
                            NP: "scale2",
                            NL: "scale6",
                            NZ: "scale4",
                            NI: "scale1",
                            NE: "scale1",
                            NG: "scale5",
                            NO: "scale5",
                            OM: "scale3",
                            PK: "scale4",
                            PA: "scale2",
                            PG: "scale1",
                            PY: "scale2",
                            PE: "scale4",
                            PH: "scale4",
                            PL: "scale10",
                            PT: "scale5",
                            QA: "scale4",
                            RO: "scale4",
                            RU: "scale7",
                            RW: "scale1",
                            WS: "scale1",
                            ST: "scale1",
                            SA: "scale5",
                            SN: "scale2",
                            RS: "scale2",
                            SC: "scale1",
                            SL: "scale1",
                            SG: "scale5",
                            SK: "scale3",
                            SI: "scale2",
                            SB: "scale1",
                            ZA: "scale5",
                            ES: "scale7",
                            LK: "scale2",
                            KN: "scale1",
                            LC: "scale1",
                            VC: "scale1",
                            SD: "scale3",
                            SR: "scale1",
                            SZ: "scale1",
                            SE: "scale5",
                            CH: "scale6",
                            SY: "scale3",
                            TW: "scale5",
                            TJ: "scale1",
                            TZ: "scale2",
                            TH: "scale5",
                            TL: "scale1",
                            TG: "scale1",
                            TO: "scale1",
                            TT: "scale2",
                            TN: "scale2",
                            TR: "scale6",
                            TM: "scale1",
                            UG: "scale2",
                            UA: "scale4",
                            AE: "scale5",
                            GB: "scale8",
                            US: "scale10",
                            UY: "scale2",
                            UZ: "scale2",
                            VU: "scale1",
                            VE: "scale5",
                            VN: "scale4",
                            YE: "scale2",
                            ZM: "scale2",
                            ZW: "scale1",
                        },
                    }, ],
                },
            });
            window.addEventListener("resize", () => {
                map.updateSize();
            });
        });